config/routes.rb
Rails.application.routes.draw do
  root to: 'batches#index'

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :batches do
    resources :students
  end

  resources :students do
    resources :evaluations
  end


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/batch.rb
class Batch < ApplicationRecord
  has_many :students, dependent: :destroy

  validates :code, presence: true, uniqueness: true
  validates :starts_at, presence: true
  validates :ends_at, presence: true

  def self.order_by_number
    order :code
  end



  def ask_question
    green_student = []
    red_student = []
    yellow_student = []
    students.each do |student|

      if !student.evaluations.any?
        red_student.push(student)
      else
      student.evaluations.last(1).each do |student_evaluation|

        if student_evaluation.color_code === "green"
          green_student.push(student)
       elsif student_evaluation.color_code === "red"
          red_student.push(student)
        elsif student_evaluation.color_code === "yellow"
          yellow_student.push(student)

        end
      end

      end
    end
    random_pick = rand()
    case
    when random_pick <= 0.17
      return " " if !green_student.any?
      green_student.sample
    when random_pick <= 0.50
      return " " if !yellow_student.any?
      yellow_student.sample
    when random_pick <= 1.0
      return " " if !red_student.any?
      red_student.sample

    end



  end


end

app/models/evaluation.rb
class Evaluation < ApplicationRecord
  belongs_to :student

   validates :day, uniqueness: {scope: :student_id}
   validates :color_code, presence: true
   validates :remarks, presence: true
end

app/models/student.rb
class Student < ApplicationRecord
  belongs_to :batch
  has_many :evaluations, dependent: :destroy

  

  validates :name, presence: true
  validates :image_url, presence:true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/batches_controller.rb
class BatchesController < ApplicationController
  before_action :authenticate_user!
  def index
    @batches = Batch.all.order_by_number
  end

  def show

    @batch = Batch.find(params[:id])

  end

  def new
    @batch =Batch.new
  end



 def create
   @batch = Batch.new(batch_params)
   if @batch.save
   redirect_to batches_path, notice: 'Batch added'
   else
   render :new
 end

 end

 private
 def batch_params
     params.require(:batch).permit(:code, :starts_at, :ends_at)
 end


end

app/controllers/evaluations_controller.rb
class EvaluationsController < ApplicationController


  def create
    if params[:save_next]
    @student = Student.find(params[:student_id])
    @new_evaluation = Evaluation.new(evaluation_params)
    @new_evaluation.student_id = params[:student_id]
        if  @new_evaluation.save
            @student_next = Student.where('id > ?', params[:student_id]).first
            redirect_to batch_student_path(@student_next.batch, @student_next.id)
        else
          redirect_to @student.batch, notice: 'Please check the details'
        end

    else
    @student = Student.find(params[:student_id])
    @new_evaluation = Evaluation.new(evaluation_params)
    @new_evaluation.student_id = params[:student_id]
       if @new_evaluation.save
         redirect_to @student.batch
       else
         redirect_to @student.batch, notice: 'Please check the details'
       end
  end
end

def edit
  @student = Student.find(params[:student_id])
  @evaluation = Evaluation.find(params[:id])
end

def update
    @evaluation = Evaluation.find(params[:id])

    if @evaluation.update_attributes(evaluation_params)
      redirect_to @evaluation.student, notice: 'Successfully updated'
    else
      redirect_to @evaluation.student, notice: 'Please check the details'
    end
end



  private

  def set_student
    @student = Student.find(params[:student_id])
  end

  def evaluation_params
      params.require(:evaluation).permit(:day, :color_code, :remarks, :student_id)
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController



def show
    @student = Student.find(params[:id])
end



def create
  @new_student = Student.new(student_params)
  @new_student.batch_id = params[:batch_id]
  if @new_student.save
  redirect_to @new_student.batch
else
  redirect_to @new_student.batch, notice: "Please fill valid details"
end


end

def edit
  batch = Batch.find(params[:batch_id])
  @student = batch.students.find(params[:id])
end

def update
    @student = Student.find(params[:id])

    if @student.update_attributes(student_params)
      redirect_to @student.batch,  notice: 'Successfully updated'
    else
      render 'edit'
    end
end

def destroy
    @batch = Batch.find(params[:batch_id])
    @student = Student.find(params[:id])
    @student.destroy
    redirect_to batch_path(@batch)
end




private
def student_params
    params.require(:student).permit(:name, :image_url, :batch_id)
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/batches_helper.rb
module BatchesHelper
end

app/helpers/evaluations_helper.rb
module EvaluationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/views/batches/_batch_form.html.erb
<%= form_for @batch, html: { multipart: true } do |f| %>


<% if @batch.errors.any? %>
  <div>
    <ul>
    <% @batch.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<div class = "row">

  <div class="panel panel-warning col-md-8 col-md-offset-2">

      <div class="panel-heading text-center">
        <h3>New Batch</h3>
      </div>


      <div class="panel-body text-center">
        <div class="form-group">
        <table class = "table table-striped">
          <tr>
            <td class="columheader"> Batch </td>
            <td class="columheader"> Start Date </td>
            <td class="columheader"> End Date </td>
          </tr>



            <tr>
            <td><%= f.text_field :code, placeholder: "Add batch number" %></td>
            <td><%= f.date_select :starts_at %></td>
            <td><%= f.date_select :ends_at %></td>
          </tr>

      </table>
        </div>

        <div class="actions">
         <%= f.submit "Add new batch", class: "btn btn-success" %>
        </div>
      <span class="pull-left"><%= link_to "Back", batches_path %></span>

        <% end %>

     </div>
   </div>

 </div>

app/views/batches/_form.html.erb
<%= form_for [@batch, @batch.students.new] do |f| %>


      <div class="row text-center">

        <div class="form-group">
        
            <label>Student name :</label>
            <%= f.text_field :name, placeholder: "Add student name" %>
            <label>Student pic :</label>
            <%= f.text_field :image_url, placeholder: "Add image url" %>
        </div>

        <div class="actions">
         <%= f.submit "Add new student", class: "btn btn-success" %>
        </div>

        <% end %>

     </div>

app/views/batches/_random_pick.html.erb
<button type="button" class="btn btn-default btn-md" data-toggle="modal" data-target="#myModal">
  ASK QUESTION
</button>

 <!-- Modal -->
 <div class="modal fade" id="myModal" role="dialog">
   <div class="modal-dialog">

     <!-- Modal content-->
     <div class="modal-content">

       <div class="modal-header">

         <h4 class="modal-title">Ask Question to :{)</h4>

       </div>

       <div class="modal-body text-center">

         <% picked_student = @batch.ask_question %>
         <% if picked_student == " " %>
         <h1>Oops!!! Pick another student</h1>
          <% else %>
         <h2><%= picked_student.name %></h2>
         <%= image_tag(picked_student.image_url,class: 'img-rounded',width: '150px', height: '150px') %>
         <% end %>
       </div>

       <div class="modal-footer">
         <%=link_to "Close",batch_path(@batch) %>
       </div>

     </div>

   </div>
</div>

app/views/batches/index.html.erb
<div class = "row">

  <div class="panel panel-warning col-md-6 col-md-offset-3">

      <div class="panel-heading text-center">
        <h3>Batches</h3>
      </div>

      <div class="panel-body text-center">

        <table class = "table table-striped">
          <tr>
            <td class="columheader"> Batch </td>
            <td class="columheader"> Start Date </td>
            <td class="columheader"> End Date </td>
          </tr>


        <% @batches.each do |batch| %>
        <tr>
            <td><%= link_to "Batch #{batch.code}", batch_path(batch) %></td>
              <td> <%= batch.starts_at.strftime("%d/%m/%Y") %></td>
               <td> <%= batch.ends_at.strftime("%d/%m/%Y") %> </td>
          </tr>


        <% end %>

      </table>
      <p><%= link_to "Add new batch", new_batch_path, class: "btn btn-success" %></p>
      </div>

    </div>

</div>

app/views/batches/new.html.erb
<%= render "batch_form" %>

app/views/batches/show.html.erb
<div class = "row">

  <div class="panel panel-warning col-md-6 col-md-offset-3">

      <div class="panel-heading text-center">
        <h3>Students</h3>
      </div>
      <% if !@batch.students.any?  %>
      <h2 class="text-center"> No students added yet </h2>
      <div>
        <%= render 'form' %>
      </div>
      <% else %>


      <% green_code = 0 %>
      <% yellow_code = 0 %>
      <% red_code = 0 %>
      <% student_count =0 %>
      <% @batch.students.each do |student| %>
      <% student.evaluations.last(1).each do |student_evaluation| %>
          <% if student_evaluation.color_code === "green"%>
          <% green_code = green_code + 1 %>
          <% student_count = student_count + 1 %>
          <% elsif student_evaluation.color_code === "yellow" %>
          <% yellow_code = yellow_code + 1 %>
          <% student_count = student_count + 1 %>
          <% elsif student_evaluation.color_code === "red" %>
          <% red_code = red_code + 1 %>
          <% student_count = student_count + 1 %>

        <% end %>
      <% end %>
     <% end %>

      <% average_green = (green_code.fdiv(student_count)) * 100 %>
      <% average_yellow = (yellow_code.fdiv(student_count)) * 100 %>
      <% average_red = (red_code.fdiv(student_count)) * 100 %>

      <div class="progress">
        <div class="progress-bar progress-bar-striped active progress-bar-success" role="progressbar" style="width:<%= average_green %>%"></div>
        <div class="progress-bar progress-bar-striped active progress-bar-warning" role="progressbar" style="width:<%= average_yellow %>%"></div>
        <div class="progress-bar progress-bar-striped active progress-bar-danger" role="progressbar" style="width:<%= average_red %>%"></div>
     </div>
     <div>
       <%= render 'random_pick' %>
     </div>

      <div class="panel-body text-center">
        <table style="width:400px" align="center">
        <% @batch.students.each do |student| %>
           <tr style="height:130px;">
            <td><%= link_to image_tag(student.image_url,class: 'img-rounded',width: '100px', height: '100px'), batch_student_path(@batch, student)  %></td>
            <td><h3><%=link_to student.name, batch_student_path(@batch, student) %></h3></td>
             <td align="center">
               <h4>
            <% student.evaluations.last(1).each do |student_evaluation| %>
                <% if student_evaluation.color_code === "green"%>
                <svg width="40" height="30">
                <rect width="40" height="30" style="fill:rgb(0,255,0);stroke-width:3;stroke:rgb(0,0,0)" />
                </svg>

                <% elsif student_evaluation.color_code === "yellow" %>
                <svg width="40" height="30">
                <rect width="40" height="30" style="fill:rgb(255,204,0);stroke-width:3;stroke:rgb(0,0,0)" />
                </svg>

                <% elsif student_evaluation.color_code === "red" %>
                <svg width="40" height="30">
                <rect width="40" height="30" style="fill:rgb(255,0,0);stroke-width:3;stroke:rgb(0,0,0)" />
                </svg>

                <% else %>
                <p> Yet to add your progress.... </p>
                <% end %>

            <% end %>
          </h4>
          </td>

          <td><h4><%= link_to '<i class="glyphicon glyphicon-pencil" style="color: rgb(0,255,0)"></i>'.html_safe, edit_batch_student_path(@batch, student) %>
          <%= link_to '<i class="glyphicon glyphicon-trash" style="color: rgb(255,0,0)"></i>'.html_safe, batch_student_path(@batch, student),
          method: :delete, data: { confirm: "Are you sure?" } %></h4></td>


        </tr>

        <% end %>

      </table>



      </div>

      <div>
        <%= render 'form' %>
      </div>

    <% end %>

    </div>

</div>

app/views/evaluations/_form_edit.html.erb
<%= form_for [@student, @evaluation] do |f| %>


  <% if @evaluation.errors.any? %>
    <div>
      <ul>
      <% @evaluation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


      <div class="row text-center">

        <div class="form-group">
            <p><label>Select day:</label></p>
            <%= f.date_select :day, class: "form-control" %>

            <p>Select the color code </p>

            <div>
                <%= f.radio_button :color_code, "green" %>
                <svg width="40" height="30">
                <rect width="40" height="30" style="fill:rgb(0,255,0);stroke-width:3;stroke:rgb(0,0,0)" />
                </svg>
                <br />


                <%= f.radio_button :color_code, "yellow" %>
                <svg width="40" height="30">
                <rect width="40" height="30" style="fill:rgb(255,69,0);stroke-width:3;stroke:rgb(0,0,0)" />
                </svg>
                <br />

                <%= f.radio_button :color_code, "red" %>
                <svg width="40" height="30">
                <rect width="40" height="30" style="fill:rgb(255,0,0);stroke-width:3;stroke:rgb(0,0,0)" />
                </svg>
                <br />

            </div>

            <label>Remarks</label>
            <%= f.text_area :remarks, placeholder: "Add Remarks" %>


        </div>

        <div class="actions">
         <%= f.submit "Update", class: "btn btn-success" %>
       </div>

       <% end %>

     </div>

app/views/evaluations/edit.html.erb
<div class = "row">
  <%= render 'form_edit' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EvaluationTool</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
   <%= render "shared/navbar" %>
 <p class="notice"><%= notice %></p>
 <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Welcome to Student Evaluation Tool</h1>

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <% if user_signed_in? %>
      <%= link_to "Student Evaluation", batches_path, class: "navbar-brand" %>
       <% end %>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">

        <% if !user_signed_in? %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>

            <ul class="dropdown-menu">
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/shared/_validation_errors.html.erb
<p class=notice color_red><%= notice %> </p>

app/views/students/_form.html.erb
<%= form_for [@student, @student.evaluations.new] do |f| %>


      <div class="row text-center">

        <div class="form-group">
            <p><label>Select day:</label></p>
            <%= f.date_select :day, class: "form-control" %>

            <p>Select the color code </p>

            <div>
                <%= f.radio_button :color_code, "green" %>
                <svg width="40" height="30">
                <rect width="40" height="30" style="fill:rgb(0,255,0);stroke-width:3;stroke:rgb(0,0,0)" />
                </svg>
                <br />


                <%= f.radio_button :color_code, "yellow" %>
                <svg width="40" height="30">
                <rect width="40" height="30" style="fill:rgb(255,69,0);stroke-width:3;stroke:rgb(0,0,0)" />
                </svg>
                <br />

                <%= f.radio_button :color_code, "red" %>
                <svg width="40" height="30">
                <rect width="40" height="30" style="fill:rgb(255,0,0);stroke-width:3;stroke:rgb(0,0,0)" />
                </svg>
                <br />

            </div>

            <label>Remarks</label>
            <%= f.text_area :remarks, placeholder: "Add Remarks" %>


        </div>

        <div class="actions">
         <%= f.submit "Save", class: "btn btn-success" %>
         <%= f.submit "Save and next", class: "btn btn-success", name: "save_next" %>

        </div>

        <% end %>

     </div>

app/views/students/_student_edit_form.html.erb
<%= form_for [@batch, @student] do |f| %>

  <% if @student.errors.any? %>
    <div>
      <ul>
      <% @student.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


      <div class="row text-center">

        <div class="form-group">
            <label>Student name :</label>
            <%= f.text_field :name, placeholder: "Add student name" %>
            <label>Student pic :</label>
            <%= f.text_field :image_url, placeholder: "Add image url" %>
        </div>

        <div class="actions">
         <%= f.submit "Update", class: "btn btn-success" %>
        </div>

        <% end %>

     </div>

app/views/students/edit.html.erb
<div class = "row">
  <%= render "student_edit_form" %>
</div>

app/views/students/index.html.erb
<h1>hello</h1>

app/views/students/show.html.erb
<div class = "row">

  <div class="panel panel-warning col-md-6 col-md-offset-3">

      <div class="panel-heading text-center">
        <h3>Student Evaluation</h3>
      </div>

      <div class="panel-body text-center">
        <table style="width:400px" align="center">
          <tr>
              <td><%= image_tag(@student.image_url,class: 'img-rounded',width: '100px', height: '100px')  %></td>
        <td><h3><%= @student.name %></h4></td>
        <td><h3>Batch<%= @student.batch.code %></h3></td>
      
        <td>
        <% @student.evaluations.each do |evaluation| %>

            <% if evaluation.color_code === "green"%>
             <%= link_to "<button class='btn btn-success btn-lg'>  </button>".html_safe, edit_student_evaluation_path(@student, evaluation) %>

            <% elsif evaluation.color_code === "yellow" %>
            <%= link_to "<button class='btn btn-warning btn-lg'></button>".html_safe, edit_student_evaluation_path(@student, evaluation) %>

            <% elsif evaluation.color_code === "red" %>
            <%= link_to "<button class='btn btn-danger btn-lg'></button>".html_safe, edit_student_evaluation_path(@student, evaluation) %>
            <% end %>

        <% end %>
      </td>
    </tr>
  </table>


      </div>
      <div>
        <%= render 'form' %>

      </div>



    </div>

</div>